# sonar-project.properties
# SonarQube project configuration
sonar.projectKey=my-fastapi-project
sonar.projectName=My FastAPI Project
sonar.projectVersion=1.0

# Source code information
sonar.sources=app           
sonar.language=python

# Exclude specific files/folders (optional)
sonar.exclusions=**/tests/**,**/__pycache__/**

# SonarQube server URL and authentication token
sonar.host.url=http://localhost:9000
sonar.token=sqa_847b385d9d4c4bb23bdfb7be413c5730c82ffc21
